### ISSUE TITLE
Model create error (invalid time delta value)

### ISSUE THREAD

**Issue by el-tanito** [vsergeyev/loudml-grafana-app#13]
Hello, I am having an error (invalid time delta value) while creating a baseline.

Am I  doing something wrong?

![model create error](https://user-images.githubusercontent.com/62558615/88047326-c10f0d00-cb51-11ea-987e-a4b56126e77a.JPG)

**Comment by vsergeyev** [comment]
Hello, It may be a bug. 

Could you please also send a screenshot of panel settings. E.g. metric, group by, fill. 

Thank you for reporting this issue!

V.

**Comment by el-tanito** [comment]
@vsergeyev, below are the configuration details.


![config](https://user-images.githubusercontent.com/62558615/88081390-99836900-cb80-11ea-86fb-04d7f3cd4c61.JPG)


If I change the configuration parameters (E.g., group by, fill) another error message appears.


![](https://user-images.githubusercontent.com/62558615/88082895-a7d28480-cb82-11ea-9c4f-8449296c2944.JPG)

**Comment by vsergeyev** [comment]
Thank you,

It looks like a bug. I’ll look for a way to fix it. 

As a workaround - you may choose some value in seconds/minutes in GROUP BY time()

This will force it to use selected value. Ex. - 10s or so. 

V.

**Comment by el-tanito** [comment]
@vsergeyev , I tried to force the group by time variable, but it doesn't work.

Inside the configuration file (loudm.yml) I have defined the two buckets. On grafana I then selected database name. 
Is it correct?

![buckets](https://user-images.githubusercontent.com/62558615/88154619-60420c00-cc07-11ea-872c-e69eafe04dc3.JPG)

#### loudml.yml
```
 buckets:

 # Input bucket
 - name: welding
   type: influxdb
   addr: 127.0.0.1:8086
   database: Marelli
   retention_policy: autogen
   measurement: loudml

 # Output bucket
 - name: loudml
   type: influxdb
   addr: 127.0.0.1:8086
   database: loudml_db
   retention_policy: autogen
   measurement: loudml
   annotation_db: loudmlannotations
   
storage:
  path: /var/lib/loudml

server:
  listen: 127.0.0.1:8077
```
#### docker-compose.yml
This is the mapping between host and container within the LoudML service

>      volumes:
>       - loudml-storage:/var/lib/loudml
>       - ./loudml/loudml.yml:/etc/loudml/loudml.yml:ro
